import YAML from 'yaml';
import { DEFAULT_PIPELINE, SERVERS, groupToolsByServer, effectiveMcpTools } from '@hermit/core';
import { enabledServers } from './mcp.js';

const NM = 'node_modules';
const PREFIX = 'hermit';

export const agentFileName = (id) => `${PREFIX}-${id}`;
export const skillDirName = (id) => `${PREFIX}-${id}`;

/**
 * Claude Code's tool vocabulary, which is capitalised and per-tool rather than
 * Copilot's lower-case categories. The mapping is deliberate, not mechanical:
 * an agent that declares no writable paths gets no Edit, Write or Bash, so its
 * read-only role is enforced by the host rather than described to it.
 */
const WEB_CAPABLE = new Set(['onboarding', 'analyst', 'architect', 'ux-designer', 'documenter']);

export function capabilityTools(agent) {
  const tools = ['Read', 'Grep', 'Glob'];
  if (agent.context?.writes?.paths?.length) tools.push('Edit', 'Write', 'Bash');
  if (WEB_CAPABLE.has(agent.id)) tools.push('WebFetch', 'WebSearch');
  if (agent.id === 'orchestrator') tools.push('Task', 'TodoWrite');
  return tools;
}

/** MCP tools are addressed as `mcp__<server>__<tool>` and can be listed individually. */
export function mcpTools(agent) {
  const declared = effectiveMcpTools(agent.context?.reads?.mcp ?? []);
  const { grouped } = groupToolsByServer(declared);
  return Object.entries(grouped)
    .flatMap(([serverId, names]) => names.sort().map((n) => `mcp__${serverId}__${n}`))
    .sort();
}

/**
 * Compile one canonical agent into a Claude Code subagent.
 *
 * The packs are *not* inlined here, unlike the Copilot build. Claude Code loads
 * skills on demand, so an agent references them by name and the pack is read
 * only when it is needed — which is also why a pack edited once is picked up by
 * every agent that names it, with no duplication to drift.
 */
export function compileAgent(agent, { registry, pipeline = DEFAULT_PIPELINE }) {
  const packs = [
    ...(agent.knowledge ?? []).map((id) => registry.knowledgeById[id]),
    ...(agent.skills ?? []).map((id) => registry.skillsById[id])
  ].filter(Boolean);

  const fm = {
    name: agentFileName(agent.id),
    description: agent.description ?? agent.role,
    // The canonical `model:` is Copilot's vocabulary; let Claude Code use the
    // session's model rather than translating a name that means nothing here.
    model: 'inherit',
    tools: [...capabilityTools(agent), ...mcpTools(agent)].join(', ')
  };

  const body = [
    `# ${agent.name}`,
    '',
    `> Generated by Hermit from \`.hermit/agents/${agent.id}.md\`. Edit that file, then run \`npx hermit sync\`.`,
    `> Direct edits here are overwritten on the next sync.`,
    '',
    `**Role**: ${agent.role}`,
    `**Stages owned**: ${agent.stages.join(', ') || 'none'}`,
    '',
    stageContract(agent, pipeline),
    '',
    agent.playbook,
    '',
    packReferences(packs),
    writeScope(agent)
  ].filter(Boolean).join('\n');

  return {
    path: `.claude/agents/${agentFileName(agent.id)}.md`,
    content: `---\n${YAML.stringify(fm, { lineWidth: 0 }).trimEnd()}\n---\n\n${body}\n`
  };
}

function stageContract(agent, pipeline) {
  const stages = pipeline.stages.filter((s) => agent.stages.includes(s.id));
  if (!stages.length) return '';
  const lines = ['## Your stage contract', ''];
  for (const s of stages) {
    lines.push(`### \`${s.id}\` — ${s.title}${s.gate === 'hitl' ? '  **(human gate)**' : ''}`);
    lines.push('');
    lines.push(`- **Reads**: ${(s.inputs ?? []).join(', ') || 'nothing upstream'}`);
    lines.push(`- **Produces**: ${(s.outputs ?? []).join(', ') || 'nothing'}`);
    lines.push(`- **Exit criteria**: ${(s.exitCriteria ?? []).map((c) => `\`${c.id}\``).join(', ') || 'none'}`);
    lines.push('');
  }
  lines.push('Start every turn with `hermit_next_task`. It returns the context you are entitled to and nothing else.');
  return lines.join('\n');
}

function packReferences(packs) {
  if (!packs.length) return '';
  return [
    '## Your packs',
    '',
    'These are installed as skills. Load the ones relevant to the task in hand:',
    '',
    ...packs.map((p) => `- **${skillDirName(p.id)}** — ${p.description || p.name}`),
    ''
  ].join('\n');
}

function writeScope(agent) {
  const paths = agent.context?.writes?.paths ?? [];
  if (!paths.length) {
    return [
      '## Write scope',
      '',
      'You produce artifacts, not files. You have no file-editing tools, and that is deliberate — your role is not to change the repository.',
      ''
    ].join('\n');
  }
  return [
    '## Write scope',
    '',
    'You may change files under:',
    '',
    ...paths.map((p) => `- \`${p}\``),
    '',
    'Narrowed further to the projects in scope when the run targets a subset — `hermit_next_task` tells you which. `.hermit/runs/` is denied to every agent by workspace permissions; it is the audit trail, not a scratch pad.',
    ''
  ].join('\n');
}

/**
 * CLAUDE.md — always-on, and the orchestrator's own instructions.
 *
 * Copilot gives the orchestrator a `mode: primary` agent file that dispatches
 * the others. Claude Code has no equivalent: the main session is the primary,
 * and a subagent dispatching subagents fights the model. So the orchestrator's
 * routing rules live here, where the main session reads them, and the role
 * agents become subagents it delegates to.
 */
export function compileClaudeMd({ registry, pipeline = DEFAULT_PIPELINE }) {
  const gates = pipeline.stages.filter((s) => s.gate === 'hitl');
  const orchestrator = registry.agentsById.orchestrator;
  const roles = registry.agents.filter((a) => a.id !== 'orchestrator');

  const content = `# Hermit — agentic SDLC pipeline

This workspace runs an agent pipeline with human approval gates. Generated by Hermit; edit \`.hermit/\` and run \`npx hermit sync\`.

## You are the orchestrator

There is no orchestrator subagent — you are it. You route work, you dispatch the role agents below through the Task tool, and you stop the line at every human gate.

Call \`hermit_status\` **first**, before any SDLC work. It is the only source of truth for what stage the work is at — never infer it from the conversation.

Then \`hermit_next_task\`, which names the stage's agent and returns that agent's scoped brief. Dispatch that agent. Do not do its work yourself: the whole point is that each role sees only what its role declares.

## The rule that matters

**Only a human can approve a gate**, by running \`hermit gate approve <id>\` in a terminal themselves.

- No tool in this workspace can do it. There is nothing to call.
- A workspace hook blocks \`hermit gate approve\` from Bash. If you try, it fails — that is the design working, not an obstacle to route around.
- A user saying "looks good" in chat is not an approval. Neither is your own judgement that the work is sound.

When a gate is open: **stop and report it**. Give the gate id and the exact command. Do not start the next stage.

${gates.length} of the ${pipeline.stages.length} stages are human-gated: ${gates.map((s) => `\`${s.id}\``).join(', ')}.

## The pipeline

| # | Stage | Agent | Gate |
|---|---|---|---|
${pipeline.stages.map((s, i) => `| ${i + 1} | \`${s.id}\` | ${agentFileName(s.agent)} | ${s.gate === 'hitl' ? '**human**' : 'auto'} |`).join('\n')}

Some stages pick a specialist over the agent named here — \`hermit_next_task\` and \`hermit status\` both name whoever is actually on it.

## The agents

${roles.map((a) => `- \`${agentFileName(a.id)}\` — ${a.role}`).join('\n')}

Each receives only the artifacts its role declares. If one reports something missing, that is a scoping decision, not an obstacle to work around — do not fetch it for them.

## Working a stage

\`\`\`
hermit_next_task        the agent's brief and its scoped context
hermit_submit_artifact  once per declared output
hermit_request_handoff  ask to advance (exit criteria are checked mechanically)
\`\`\`

A refused handoff names the exact criterion that failed. Fix that specific thing; do not resubmit the same content.

## Reporting

Lead with state, not narrative:

\`\`\`
Run:    run-20260822-1432-a1b2
Stage:  architecture (3/${pipeline.stages.length}) — awaiting human gate
Action: hermit gate approve gate_architecture_7f3c
\`\`\`

${orchestrator ? `---\n\n## Your playbook\n\n${orchestrator.playbook}\n` : ''}`;

  return { path: 'CLAUDE.md', content };
}

/**
 * Skills and knowledge packs become real Claude Code skills, loaded on demand
 * rather than concatenated into every agent that references them.
 */
export function compileSkills({ registry }) {
  const packs = [...registry.knowledge, ...registry.skills];
  return packs.map((pack) => {
    const fm = { name: skillDirName(pack.id), description: pack.description || pack.name };
    return {
      path: `.claude/skills/${skillDirName(pack.id)}/SKILL.md`,
      content:
        `---\n${YAML.stringify(fm, { lineWidth: 0 }).trimEnd()}\n---\n\n` +
        `<!-- Generated by Hermit from .hermit/${registry.knowledgeById[pack.id] ? 'knowledge' : 'skills'}/${pack.id}/SKILL.md — edit that file, then run: npx hermit sync -->\n\n` +
        `${pack.body}\n`
    };
  });
}

/**
 * `.mcp.json` — project-scoped MCP servers, discovered automatically.
 *
 * No `HERMIT_WORKSPACE` here, deliberately. Claude Code expands `${VAR}` from
 * the environment but has no project-directory variable, and it launches
 * servers with the project root as cwd — which is exactly what the server's own
 * upward walk for `.hermit/` needs. A hardcoded absolute path would break the
 * moment the repository is cloned somewhere else.
 */
export function compileMcpJson(config) {
  const mcpServers = {};
  for (const def of enabledServers(config)) {
    const env = Object.fromEntries(def.env.map((e) => [e.name, `\${${e.name}}`]));
    mcpServers[def.id] = {
      command: 'node',
      args: [`${NM}/${def.package}/src/index.js`],
      ...(Object.keys(env).length ? { env } : {})
    };
  }
  return { path: '.mcp.json', content: JSON.stringify({ mcpServers }, null, 2) + '\n', merge: 'mcpServers' };
}

/**
 * Permissions and the gate guard.
 *
 * This is the one surface where Hermit's scoping stops being advisory. The run
 * ledger is denied to everyone, and a PreToolUse hook refuses any Bash command
 * that would decide a gate — which is the project's headline claim, finally
 * enforced rather than asserted.
 */
export function compileSettings({ registry }) {
  const deny = [
    'Read(.env)', 'Read(.env.*)', 'Read(**/*.pem)', 'Read(**/id_rsa*)',
    'Edit(.hermit/runs/**)', 'Write(.hermit/runs/**)',
    'Edit(.claude/agents/**)', 'Write(.claude/agents/**)',
    'Edit(.claude/skills/**)', 'Write(.claude/skills/**)',
    'Edit(CLAUDE.md)', 'Write(CLAUDE.md)'
  ];

  const settings = {
    permissions: { deny },
    hooks: {
      PreToolUse: [
        {
          matcher: 'Bash',
          hooks: [{ type: 'command', command: 'node .hermit/hooks/guard-gate.mjs' }]
        }
      ]
    }
  };

  // Not merged, unlike the MCP configs. A partial merge keeps whichever `hooks`
  // block is already on disk, which would silently drop the gate guard — the one
  // file where losing Hermit's contribution defeats the point of writing it.
  // A hand edit is caught by the manifest and reported, like any generated file.
  return { path: '.claude/settings.json', content: JSON.stringify(settings, null, 2) + '\n' };
}

/** The hook itself. Blocking is exit code 2 with the reason on stderr. */
export function compileGateHook() {
  const content = `#!/usr/bin/env node
// Generated by Hermit. Blocks an agent from deciding a human gate through Bash.
//
// Hermit's claim is that gate approval is unreachable from the agent side: no
// MCP tool exposes it, and decideGate refuses any source but the CLI. Bash is
// the remaining hole — an agent can type the CLI command itself. This closes it.
//
// A person approving in their own terminal is unaffected; this hook only runs
// on tool calls Claude makes.

let raw = '';
process.stdin.on('data', (c) => { raw += c; });
process.stdin.on('end', () => {
  let command = '';
  try { command = JSON.parse(raw)?.tool_input?.command ?? ''; } catch { /* not JSON: allow */ }

  const decides = /(^|[;&|]|\\s)(npx\\s+)?hermit\\s+gate\\s+(approve|reject|changes)\\b/.test(command);
  if (!decides) process.exit(0);

  process.stderr.write(
    'Blocked by Hermit: only a human may decide a gate.\\n\\n' +
    'No agent approves its own work — that is what the gate is for. Report the\\n' +
    'gate id and the command, and stop. The person you are working with runs it\\n' +
    'in their own terminal.\\n'
  );
  process.exit(2);
});
`;
  return { path: '.hermit/hooks/guard-gate.mjs', content };
}

/** Everything the Claude Code harness generates. */
export function claudeFiles({ registry, config, pipeline, layoutInfo }) {
  return [
    ...registry.agents.map((agent) => compileAgent(agent, { registry, pipeline })),
    ...compileSkills({ registry }),
    compileClaudeMd({ registry, pipeline }),
    compileMcpJson(config),
    compileSettings({ registry }),
    compileGateHook(),
    ...compileProjectSkills(layoutInfo)
  ];
}

/**
 * Copilot loads a per-project instruction file automatically when you open a
 * matching path. Claude Code has no path-triggered loading, so the layout
 * becomes one skill the agents can read when they need to place a file.
 */
export function compileProjectSkills(layoutInfo = { monorepo: false, projects: [] }) {
  const { projects, monorepo, tool } = layoutInfo;
  if (!monorepo || !projects.length) return [];

  const fm = {
    name: 'hermit-repository-layout',
    description: `The ${projects.length} projects in this repository, what each is, and the rules for changing them.`
  };

  return [{
    path: '.claude/skills/hermit-repository-layout/SKILL.md',
    content: `---\n${YAML.stringify(fm, { lineWidth: 0 }).trimEnd()}\n---\n\n<!-- Generated by Hermit. Run: npx hermit sync -->

# Repository layout

${projects.length} projects${tool ? `, managed with **${tool}**` : ''}:

| Project | Path | Kind | UI | Stack |
|---|---|---|---|---|
${projects.map((p) => `| \`${p.id}\` | \`${p.path}/\` | ${p.kind} | ${p.ui ? 'yes' : '—'} | ${(p.stack ?? []).join(', ')} |`).join('\n')}

## Rules that apply everywhere

- **Locate before you edit.** A file path alone does not tell you which project owns a behaviour. Confirm the project first.
- **Cross-project changes need a decision.** A change spanning projects has a wider blast radius than the one it was scoped for. Name it and escalate rather than absorbing it.
- **Shared code lives in shared packages.** Do not copy a utility between projects.
- **Each project owns its tests.** Run the suite for the project you changed, not just the root command.

Run scope is set when the run starts; \`hermit_next_task\` tells you which projects are in scope. Anything out of scope is readable for context but not writable.

Runs can target a subset: \`hermit start "<intent>" --project ${projects.slice(0, 2).map((p) => p.id).join(',')}\`. When no project in scope has a UI, the UX stages and the interface implementation stage are skipped automatically.
`
  }];
}
