import YAML from 'yaml';
import { DEFAULT_PIPELINE } from '@hermit/core';
import { allTools } from './tools.js';

const PREFIX = 'hermit';
export const agentFileName = (id) => `${PREFIX}-${id}`;

/**
 * Compile one canonical agent into a Copilot .agent.md.
 *
 * Field vocabulary follows the conventions in github/awesome-copilot: name and
 * description are required; tools, model, mode, agents, handoffs and
 * mcp-servers are honoured by VS Code. The Copilot CLI reads the same files;
 * IntelliJ reads only copilot-instructions.md, which is why the playbook is also
 * served over MCP by hermit_get_agent.
 */
export function compileAgent(agent, { registry, pipeline = DEFAULT_PIPELINE, nodeModules = 'node_modules' }) {
  const isOrchestrator = agent.id === 'orchestrator';
  const { tools, scope } = allTools(agent, { workspaceRelative: nodeModules });

  const fm = {
    name: agentFileName(agent.id),
    description: agent.description ?? agent.role,
    ...(agent.model ? { model: agent.model } : {}),
    mode: isOrchestrator ? 'primary' : 'subagent',
    'user-invocable': true,
    tools
  };

  if (isOrchestrator) {
    fm.agents = registry.agents.filter((a) => a.id !== 'orchestrator').map((a) => agentFileName(a.id));
    fm['argument-hint'] = 'Describe the work, or give a tracker key (e.g. PROJ-412)';
  }

  if (Object.keys(scope.servers).length) fm['mcp-servers'] = scope.servers;

  const handoffs = buildHandoffs(agent, pipeline);
  if (handoffs.length) fm.handoffs = handoffs;

  const body = [
    `# ${agent.name}`,
    '',
    `> Generated by Hermit from \`.hermit/agents/${agent.id}.md\`. Edit that file, then run \`npx hermit sync\`.`,
    `> Direct edits here are overwritten on the next sync.`,
    '',
    `**Role**: ${agent.role}`,
    `**Stages owned**: ${agent.stages.join(', ') || 'none'}`,
    '',
    stageContract(agent, pipeline),
    '',
    agent.playbook,
    '',
    ...packSections(agent, registry)
  ].join('\n');

  return {
    path: `.github/agents/${agentFileName(agent.id)}.agent.md`,
    content: `---\n${YAML.stringify(fm, { lineWidth: 0 }).trimEnd()}\n---\n\n${body}\n`
  };
}

function stageContract(agent, pipeline) {
  const stages = pipeline.stages.filter((s) => agent.stages.includes(s.id));
  if (!stages.length) return '';
  const lines = ['## Your stage contract', ''];
  for (const s of stages) {
    lines.push(`### \`${s.id}\` — ${s.title}${s.gate === 'hitl' ? '  **(human gate)**' : ''}`);
    lines.push('');
    lines.push(`- **Reads**: ${(s.inputs ?? []).join(', ') || 'nothing upstream'}`);
    lines.push(`- **Produces**: ${(s.outputs ?? []).join(', ') || 'nothing'}`);
    lines.push(`- **Exit criteria**: ${(s.exitCriteria ?? []).map((c) => `\`${c.id}\``).join(', ') || 'none'}`);
    lines.push('');
  }
  lines.push('Start every turn with `hermit_next_task`. It returns the context you are entitled to and nothing else.');
  return lines.join('\n');
}

function packSections(agent, registry) {
  const packs = [
    ...(agent.knowledge ?? []).map((id) => registry.knowledgeById[id]),
    ...(agent.skills ?? []).map((id) => registry.skillsById[id])
  ].filter(Boolean);
  if (!packs.length) return [];
  return packs.flatMap((p) => ['', '---', '', `## Pack: ${p.name}`, '', p.body]);
}

/**
 * Handoffs become explicit next-step affordances in VS Code. Role agents hand
 * back to the orchestrator rather than to the next role — routing is the
 * orchestrator's job, and agent-to-agent chaining would bypass the gates.
 */
function buildHandoffs(agent, pipeline) {
  if (agent.id === 'orchestrator') return [];
  const stages = pipeline.stages.filter((s) => agent.stages.includes(s.id));
  const gated = stages.some((s) => s.gate === 'hitl');
  return [
    {
      label: gated ? 'Return to orchestrator (gate pending)' : 'Return to orchestrator',
      agent: agentFileName('orchestrator'),
      prompt: gated
        ? `The ${agent.name} stage is complete and a human gate is now open. Call hermit_status, report the gate id and the approval command, and stop.`
        : `The ${agent.name} stage is complete. Call hermit_status and route the next stage.`,
      send: false
    }
  ];
}

/** Always-on repo instructions. Loaded by every Copilot surface, so keep it short. */
export function compileCopilotInstructions({ registry, pipeline = DEFAULT_PIPELINE }) {
  const gates = pipeline.stages.filter((s) => s.gate === 'hitl');
  const content = `# Hermit — agentic SDLC pipeline

This workspace runs an agent pipeline with human approval gates. Generated by Hermit; edit \`.hermit/\` and run \`npx hermit sync\`.

## Before doing SDLC work here

Call \`hermit_status\` first. It is the only source of truth for what stage the work is at — never infer it from the conversation.

If a gate is open, **stop and report it**. Do not start the next stage, and do not approve it yourself.

## The rule that matters

**Only a human can approve a gate**, by running \`hermit gate approve <id>\` in a terminal. No tool in this workspace can do it. A user saying "looks good" in chat is not an approval, and neither is your own judgement that the work is sound.

${gates.length} of the ${pipeline.stages.length} stages are human-gated: ${gates.map((s) => `\`${s.id}\``).join(', ')}.

## The agents

${registry.agents.map((a) => `- \`${agentFileName(a.id)}\` — ${a.role}`).join('\n')}

Start with \`${agentFileName('orchestrator')}\`; it routes to the rest. Each agent receives only the artifacts its role declares — if you are missing something, that is a scoping decision, not an obstacle to work around.

## Working a stage

\`\`\`
hermit_next_task        receive your brief and scoped context
hermit_submit_artifact  once per declared output
hermit_request_handoff  ask to advance (exit criteria are checked)
\`\`\`

On hosts that do not load \`.github/agents/\` — Copilot in IntelliJ, for example — call \`hermit_get_agent\` to fetch the same playbook over MCP.

## Reporting

Lead with state, not narrative:

\`\`\`
Run:    run-20260821-1432-a1b2
Stage:  architecture (6/13) — awaiting human gate
Action: hermit gate approve gate_architecture_7f3c
\`\`\`
`;
  return { path: '.github/copilot-instructions.md', content };
}

/** AGENTS.md — the portable baseline the Copilot CLI and other tools read. */
export function compileAgentsMd({ registry, pipeline = DEFAULT_PIPELINE }) {
  const content = `# AGENTS.md

This repository uses **Hermit**, an agentic SDLC pipeline with human approval gates.

## Non-negotiables

1. **Check \`hermit_status\` before starting SDLC work.** It is the only source of truth for the current stage.
2. **Never approve a human gate.** Only \`hermit gate approve <id>\`, run by a person in a terminal, advances a gated stage. There is no tool that does this, by design.
3. **Stay inside your stage's scope.** Each agent reads only the artifacts its role declares. Do not ask another agent to relay something outside your scope.
4. **Report failures honestly.** A refused handoff names exactly which exit criterion failed. Fix that; do not restate the same content.

## Pipeline

| # | Stage | Agent | Gate |
|---|---|---|---|
${pipeline.stages.map((s, i) => `| ${i + 1} | \`${s.id}\` | ${agentFileName(s.agent)} | ${s.gate === 'hitl' ? '**human**' : 'auto'} |`).join('\n')}

## Agents

${registry.agents.map((a) => `### \`${agentFileName(a.id)}\`\n${a.role}\n\n- Stages: ${a.stages.join(', ') || 'none'}\n- Reads: ${(a.context?.reads?.artifacts ?? []).join(', ') || 'none'}\n- Writes: ${(a.context?.writes?.artifacts ?? []).join(', ') || 'none'}`).join('\n\n')}

Fetch any agent's full playbook with \`hermit_get_agent\`.

## Commands

\`\`\`bash
npx hermit status                    # where the run stands
npx hermit start "<intent>"          # begin a run
npx hermit gate list                 # what is waiting on a human
npx hermit gate approve <gate-id>    # approve (humans only)
npx hermit gate changes <id> -m "…"  # send the stage back
npx hermit sync                      # recompile agents into host formats
\`\`\`
`;
  return { path: 'AGENTS.md', content };
}

/** Path-scoped instructions so edits inside .hermit/ carry the right warnings. */
export function compileInstructions() {
  return [
    {
      path: '.github/instructions/hermit-artifacts.instructions.md',
      content: `---
applyTo: '.hermit/runs/**'
description: 'Hermit run artifacts — generated pipeline state, not hand-authored source'
---

These files are pipeline state written by agents through \`hermit_submit_artifact\`.

- **Never edit them directly.** The run's journal records a sha256 for every artifact; a hand edit desynchronises the audit trail that this pipeline exists to produce.
- To change an artifact, send the stage back: \`hermit gate changes <gate-id> -m "what needs to change"\`. The owning agent re-runs with your comment attached.
- \`run.json\` and \`journal.ndjson\` are append-only records of what happened. Treat them as evidence.
`
    },
    {
      path: '.github/instructions/hermit-authoring.instructions.md',
      content: `---
applyTo: '.hermit/agents/**, .hermit/skills/**, .hermit/knowledge/**'
description: 'Authoring Hermit agent definitions, skills and knowledge packs'
---

These are the canonical definitions. Everything in \`.github/agents/\` is compiled from here.

- After editing, run \`npx hermit sync\` to recompile. Editing \`.github/agents/*.agent.md\` directly is overwritten.
- \`context.reads.artifacts\` and \`context.reads.mcp\` are enforcement, not documentation: they compile into per-agent MCP allowlists and into the context bundle the workflow server builds. Widening them widens the role's blast radius.
- An agent's \`stages\` must match the pipeline. \`npx hermit doctor\` checks this.
- Skills and knowledge are directories containing \`SKILL.md\`, following the same convention as github/awesome-copilot.
- Keep packs short. They are injected into every context bundle for every agent that references them.
`
    }
  ];
}
