import { SERVERS } from '@hermit/core';

const NM = 'node_modules';

/**
 * The three Copilot surfaces read MCP config from three different places in two
 * different shapes. All are generated from the same registry so they cannot drift.
 *
 *   VS Code       .vscode/mcp.json          { servers: { … } }, type "stdio"
 *   Copilot CLI   .copilot/mcp-config.json  { mcpServers: { … } }, type "local"
 *   IntelliJ      configured through the IDE UI — we emit setup instructions
 */
function serverEntry(def, { style }) {
  const script = `${NM}/${def.package}/src/index.js`;
  const env = Object.fromEntries(def.env.map((e) => [e.name, `\${env:${e.name}}`]));

  if (style === 'vscode') {
    return {
      type: 'stdio',
      command: 'node',
      args: [`\${workspaceFolder}/${script}`],
      cwd: '${workspaceFolder}',
      env: { HERMIT_WORKSPACE: '${workspaceFolder}', ...env }
    };
  }
  return {
    type: 'local',
    command: 'node',
    args: [script],
    tools: ['*'],
    env: Object.fromEntries(def.env.map((e) => [e.name, `$${e.name}`]))
  };
}

export function enabledServers(config) {
  const requested = config?.servers;
  const ids = Array.isArray(requested) && requested.length ? requested : Object.keys(SERVERS);
  if (!ids.includes('hermit')) ids.unshift('hermit');
  return ids.filter((id) => SERVERS[id]).map((id) => SERVERS[id]);
}

export function compileVsCodeMcp(config) {
  const servers = {};
  for (const def of enabledServers(config)) servers[def.id] = serverEntry(def, { style: 'vscode' });
  return { path: '.vscode/mcp.json', content: JSON.stringify({ servers }, null, 2) + '\n', merge: 'servers' };
}

export function compileCliMcp(config) {
  const mcpServers = {};
  for (const def of enabledServers(config)) mcpServers[def.id] = serverEntry(def, { style: 'cli' });
  return { path: '.copilot/mcp-config.json', content: JSON.stringify({ mcpServers }, null, 2) + '\n', merge: 'mcpServers' };
}

export function compileIntellijSetup(config) {
  const servers = enabledServers(config);
  const rows = servers
    .map((s) => `| \`${s.id}\` | \`node\` | \`${NM}/${s.package}/src/index.js\` | ${s.env.map((e) => `\`${e.name}\``).join(', ') || '—'} |`)
    .join('\n');

  const content = `# Hermit in JetBrains IDEs (IntelliJ IDEA)

Generated by Hermit. Re-run \`npx hermit sync\` after changing which servers are enabled.

## What works where

GitHub Copilot's three surfaces do not read the same files:

| | VS Code | Copilot CLI | IntelliJ |
|---|---|---|---|
| \`.github/copilot-instructions.md\` | yes | yes | **yes** |
| \`AGENTS.md\` | yes | yes | partial |
| \`.github/agents/*.agent.md\` | yes | yes | **no** |
| MCP servers | \`.vscode/mcp.json\` | \`.copilot/mcp-config.json\` | **IDE settings** |

IntelliJ does not load per-agent files. This is why Hermit serves every playbook over MCP as well: the pipeline behaves identically in IntelliJ, you just address agents by asking for them rather than selecting them.

## Setup

1. Install the GitHub Copilot plugin and sign in.
2. Open **Settings → Tools → GitHub Copilot → Model Context Protocol (MCP)**.
3. Add each server below. Paths are relative to the project root.

| Server | Command | Arguments | Environment |
|---|---|---|---|
${rows}

Set \`HERMIT_WORKSPACE\` to the project root on every server, so they locate \`.hermit/\` regardless of the IDE's working directory.

4. Restart the IDE and confirm the tools appear in Copilot Chat.

## Driving the pipeline from IntelliJ

Because agent files are not loaded, adopt a role explicitly:

\`\`\`
Call hermit_status. Then call hermit_get_agent with agent "orchestrator",
follow that playbook, and route the current stage.
\`\`\`

The role agent's brief comes from \`hermit_next_task\` exactly as it does in VS Code — same playbook text, same scoped context, same exit criteria.

## Gates

Gates are approved in a terminal, not in the IDE:

\`\`\`bash
npx hermit gate list
npx hermit gate approve <gate-id>
\`\`\`

This is deliberate. A gate approval must come from a person, so it lives outside every surface an agent can reach.
`;
  return { path: 'docs/hermit-intellij-setup.md', content };
}
